# Generated by Django 2.2.17 on 2020-12-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
